# Optional: Expose settings so you can do `from config import settings`
from .settings import (
    VIDEO_PATH,
    VIDEO_URL,
    VIDEO_NAME,
    VIDEO_DOWNLOAD_PATH,
    MODEL_PATH,
    MPS_TO_MPH,
    CLASSES_TO_TRACK,
    CONFIDENCE_THRESHOLD,
    RECORD_OUTPUT_VIDEO,
    RECORD_OUTPUT_DIR,
    RECORD_OUTPUT_PREFIX,
    RECORD_OUTPUT_CODEC,
    RECORD_OUTPUT_QUEUE_SIZE,
    RECORD_OUTPUT_DROP_FRAMES,
    SAVE_VEHICLE_DATA,
    SHOW_MONITORING_AREA,
)
